enabled: true
items:
  - id: 2f5f9643-2011-4e3c-9fcb-17e544c87e89
    title: 掌握 AI 的人，将成为各个领域的王者，让普通人也能驾驭 AI。
    summary: |-
      掌握 AI 的人，将成为各个领域的王者。
      让普通人也能驾驭 AI。
    date: 2023-04-27
    image: https://hyphentech.top/obsidian-assets/notices%2F2f5f964320114e3c9fcb17e544c87e89/image-01-186d7cb7b8.jpg
    image_caption: null
