enabled: true
items:
  - id: 2f5f9643-2011-4e3c-9fcb-17e544c87e89
    title: 让AI成为你的超能力
    summary: |-
      让AI成为你的超能力。
      本地部署 / 免费白嫖 / 自制软件。
    date: 2023-04-27
    image: https://hyphentech.top/obsidian-assets/notices%2F2f5f964320114e3c9fcb17e544c87e89/image-01-186d7cb7b8.jpg
    image_caption: null
